version: '3'
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - price-alert-app-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - price-alert-app-redis:/var/lib/redis/data

  price-alert-app:
    build:
      context: .
    volumes:
      - ./price-alert-app:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  price-alert-app-postgres:
  price-alert-app-redis: